### ISSUE TITLE
Battleship Model ship placement 

### ISSUE THREAD

**Issue by chrisjmendoza** [chrisjmendoza/Battleship#10]
Attempting to place a ship in A1 going south gives: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at BattleshipModel.isValidShipPlacement(BattleshipModel.java:166)
    at BattleshipSetupView.collectDataForPlayer(BattleshipSetupView.java:47)
    at BattleshipKicker.main(BattleshipKicker.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Create special case for this.

**Comment by chrisjmendoza** [comment]
Seems fixed. Nice work! :dart:
